package by.htp.les02.controller.command;

public enum CommandName {
	LOGINATION,
	GOTOREGISTRATIONPAGE,
	SAVENEWUSER,
	GOTOINDEXPAGE,
	GOTOMAINPAGE,
	LOGOUT,
	GO_TO_ONE_NEWS_PAGE,
	GO_TO_EDIT_PAGE,
	SAVE_EDIT_ONE_NEWS,
	DELETE_ONE_NEWS,
	CHANGE_LOCAL;
}
